spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:localdev}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:/db/migration/schema, classpath:/db/migration/data/dev
