application:
  developer:
    name: @team.name@
    email: @team.email@
    organisation: @team.organisation@
    organisation-url: @team.organization.url@
  license:
    name: @license.name@
    url: @license.url@

server:
  port: ${APPLICATION_PORT:9999}
  servlet:
    context-path: /@project.artifactId@
socket:
  hostname: ${SOCKET_ISO8583_HOSTNAME:localhost}
  port: ${SOCKET_ISO8583_PORT:8000}

spring:
  devtools:
    add-properties: false
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:kasda_gateway}
    username: ${DATABASE_USER:kasda_gateway}
    password: ${DATABASE_PASSWORD:kasda_gateway}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    encoding: UTF-8
    enabled: false
    baseline-on-migrate: true
    locations: classpath:/db/migration
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 3
logging:
  level:
    org.springframework: ERROR
    com.multipolar.sumsel.kasda.kasdagateway: ${LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_LOCATION:./.logs/${spring.application.name}.log}
