POST http://{{host}}:{{port}}{{context-path}}/api/payment-gateway/v1.0/transaction/validate/account-source
Content-Type: application/json

{
  "tahunAnggaran": "2020",
  "nomorSpm": "asdb",
  "namaPenerima": "qwerty",
  "bankPenerima": "zxcvb",
  "rekeningPenerima": "1234",
  "dateCreated": "12/10/20 16:16:26",
  "uraian": "bagus",
  "namaUnit": "bni",
  "namaSubUnit": "cab bni"
}
