POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=validationAccountSource&terminalId=123456
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "thn_angaran": "2020",
  "no_spm": "111111111111",
  "nama_penerima": "Dimas Maryanto",
  "bank_penerima": "BNI",
  "rekening_penerima": "22222222220",
  "date_create": "15/10/2020 16:16:00",
  "nama_unit": "Developer",
  "nama_sub_unit": "Programmer",
  "uraian": "IT"
}

### Validasi nomor rekening ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=loggingSp2d
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "thn_angaran": "2020",
  "no_spm": "111111111111",
  "nama_penerima": "Dimas Maryanto",
  "bank_penerima": "BNI",
  "rekening_penerima": "22222222220",
  "date_create": "15/10/2020 16:16:00",
  "nama_unit": "Developer",
  "nama_sub_unit": "Programmer",
  "uraian": "IT"
}

### Validasi nomor rekening ###
