POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=validationAccountSource&terminalId=123456
Content-Type: application/json

{
  "Tahun": "2020",
  "No_SPM": "111111111111",
  "Nm_Penerima": "Dimas Maryanto",
  "Bank_Penerima": "BNI",
  "Rek_Penerima": "22222222220",
  "DateCreate": "15/10/2020 16:16:00",
  "Nm_Unit": "Developer",
  "Nm_Sub_Unit": "Programmer",
  "Uraian": "IT"
}

### Validasi nomor rekening ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=loggingSP2D&terminalId=123456
Content-Type: application/json

{
  "Tahun": "2020",
  "Kd_Urusan": "1",
  "Kd_Bidang": "1",
  "Kd_Unit": "1",
  "Kd_Sub": "1",
  "No_SP2D": "123456789",
  "Kd_Rek_1": "1",
  "Kd_Rek_2": "2",
  "Kd_Rek_3": "3",
  "Kd_Rek_4": "4",
  "Kd_Rek_5": "5",
  "No_SPM": "2222222",
  "Jn_SPM": "02",
  "Nm_Rekening": "123456",
  "Nilai": "1000000"
}

### logging sp2d ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=inquirySP2D&terminalId=123456
Content-Type: application/json

{
  "Kd_Cabang": "11111",
  "Kd_Wilayah": "22222",
  "No_SP2D": "00000001234"
}

### inquiry sp2d ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=transactionSP2D&terminalId=123456
Content-Type: application/json

{
  "Kd_Cabang": "11111",
  "Kd_Wilayah": "22222",
  "No_SP2D": "00000001234",
  "Kd_Urusan": "1",
  "Kd_Bidang": "2",
  "Kd_Unit": "3",
  "Kd_Sub": "2",
  "Tahun": "2020",
  "Tgl_SP2D": "2020/10/22",
  "No_SPM": "1234091234",
  "Tgl_SPM": "2020/10/22",
  "Jn_SPM": "02",
  "Nm_Penerima": "Dimas Maryanto",
  "Keterangan": "-",
  "NPWP": "1234231432",
  "Bank_Penerima": "testing",
  "Rek_Penerima": "091234",
  "Tgl_Penguji": "2020/10/20",
  "Nm_Bank": "BNI",
  "No_Rekening": "000001010",
  "Nilai": "100000",
  "DateCreate": "2020/10/22 17:20:00",
  "Gaji": "1",
  "Nm_Unit": "asdlfkj",
  "Nm_Sub_Unit": "testing",
  "Uraian": "testing",
  "Kd_Rek_1": "1",
  "Kd_Rek_2": "2",
  "Kd_Rek_3": "3",
  "Kd_Rek_4": "3",
  "Kd_Rek_5": "3",
  "Nm_Rekening": "03"
}

### transaction sp2d ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=notificationSP2D&terminalId=123456
Content-Type: application/json

{
  "Kd_Cabang": "11111",
  "Kd_Wilayah": "22222",
  "No_Bukti": "00000001234",
  "Tgl_Transaksi": "20/10/22",
  "Tgl_Bukti": "20/10/22",
  "id_bil_1": "1",
  "id_bil_2": "1",
  "id_bil_3": "1",
  "id_bil_4": "1",
  "id_bil_5": "1",
  "id_bil_6": "1",
  "id_bil_7": "1",
  "id_bil_8": "1",
  "id_bil_9": "1",
  "id_bil_10": "1",
  "ntpn_1": "1",
  "ntpn_2": "1",
  "ntpn_3": "1",
  "ntpn_4": "1",
  "ntpn_5": "1",
  "ntpn_6": "1",
  "ntpn_7": "1",
  "ntpn_8": "1",
  "ntpn_9": "1",
  "ntpn_10": "1"
}

### notif sp2d ###
