POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=validationAccountSource&terminalId=123456
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "thn_angaran": "2020",
  "no_spm": "111111111111",
  "nama_penerima": "Dimas Maryanto",
  "bank_penerima": "BNI",
  "rekening_penerima": "22222222220",
  "date_create": "15/10/2020 16:16:00",
  "nama_unit": "Developer",
  "nama_sub_unit": "Programmer",
  "uraian": "IT"
}

### Validasi nomor rekening ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=loggingSPJ&terminalId=123456
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "kode_urusan": "1",
  "kode_bidang": "1",
  "kode_unit": "1",
  "kode_sub": "1",
  "thn_angaran": "2020",
  "no_bukti": "123456789",
  "tanngal_bukti": "2020/10/22 17:36:00",
  "jenis_dokument": "1",
  "nama_penerima": "Dimas Maryanto",
  "keterangan": "3",
  "npwp": "10010101010",
  "bank_penerima": "BNI",
  "rekening_penerima": "2222222",
  "nama_bank": "BANK SUMSEL BABEL",
  "no_rekening": "123456",
  "nilai": "1000000",
  "date_created": "2020/10/22 17:37:00",
  "cair": "0",
  "tanggal_cair": "2020/10/22 17:37:00",
  "nama_unit": "BNI",
  "nama_sub_unit": "BANKING",
  "uraian": "PEMBAYARAN",
  "kode_rek_1": "1",
  "kode_rek_2": "1",
  "kode_rek_3": "1",
  "kode_rek_4": "1",
  "kode_rek_5": "1",
  "nama_rekening": "1"
}

### logging sp2d ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=inquirySPJ&terminalId=123456
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "kode_cabang": "11111",
  "kode_wilayah": "22222",
  "no_bukti": "00000001234"
}

### inquiry spj ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=transactionSPJ&terminalId=123456
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "kode_cabang": "11111",
  "kode_wilayah": "22222",
  "tahun": "2020",
  "no_bukti": "00000001234",
  "jenis_dokument": "0000",
  "kode_urusan": "1",
  "kode_bidang": "2",
  "kode_unit": "3",
  "kode_sub": "2",
  "tanggal_bukti": "2020/10/22 17:51:00",
  "nama_penerima": "Dimas Maryanto",
  "bank_penerima": "testing",
  "rekening_penerima": "091234",
  "npwp": "1234231432",
  "nama_bank": "BNI",
  "no_rekening": "000001010",
  "nilai": "100000",
  "date_create": "2020/10/22 17:20:00",
  "tanggal_cair": "2020/10/22 17:20:00",
  "nama_unit": "asdlfkj",
  "nama_sub_unit": "testing",
  "uraian": "testing",
  "thn_angaran": "2020",
  "kode_rek_1": "1",
  "kode_rek_2": "2",
  "kode_rek_3": "3",
  "kode_rek_4": "3",
  "kode_rek_5": "3",
  "no_spm": "1234091234",
  "keterangan": "-",
  "nama_rekening": "03"
}

### transaction spj ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1.0/request/transaction?transactionType=notificationSPJ&terminalId=123456
Content-Type: application/json

{
  "card_no": "9999999999999999",
  "kode_cabang": "11111",
  "kode_wilayah": "22222",
  "no_bukti": "00000001234",
  "tanggal_transaksi": "20/10/22",
  "tanggal_bukti": "20/10/22",
  "id_bil_1": "1",
  "id_bil_2": "1",
  "id_bil_3": "1",
  "id_bil_4": "1",
  "id_bil_5": "1",
  "id_bil_6": "1",
  "id_bil_7": "1",
  "id_bil_8": "1",
  "id_bil_9": "1",
  "id_bil_10": "1",
  "ntpn_1": "1",
  "ntpn_2": "1",
  "ntpn_3": "1",
  "ntpn_4": "1",
  "ntpn_5": "1",
  "ntpn_6": "1",
  "ntpn_7": "1",
  "ntpn_8": "1",
  "ntpn_9": "1",
  "ntpn_10": "1"
}

### notif spm ###
